# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 01:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codAsig', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('codDpto', models.CharField(choices=[(b'EA', b'Estudios Ambientales'), (b'CE', b'Ciencias Econ\xc3\xb3micas y Administrativas'), (b'CC', b'Ciencia y Tecnolog\xc3\xada del Comportamiento'), (b'FIS', b'F\xc3\xadsica'), (b'QM', b'Qu\xc3\xadmica'), (b'MC', b'Mec\xc3\xa1nica'), (b'MA', b'Matem\xc3\xa1ticas Puras y Aplicadas'), (b'CI', b'Computaci\xc3\xb3n y Ciencias de la Informaci\xc3\xb3n'), (b'CO', b'C\xc3\xb3mputo Cient\xc3\xadfico y Estad\xc3\xadstica'), (b'EC', b'Electr\xc3\xb3nica y Circuitos'), (b'TF', b'Termodin\xc3\xa1mica y Fen\xc3\xb3menos de Transferencia'), (b'PS', b'Procesos y Sistemas'), (b'MT', b'Ciencias de los Materiales'), (b'GC', b'Ciencias de la Tierra'), (b'LL', b'Lengua y Literatura'), (b'ID', b'Idiomas'), (b'FLX', b'Filosof\xc3\xada'), (b'CS', b'Ciencias Sociales'), (b'DA', b'Dise\xc3\xb1o Arquitectura y Artes Pl\xc3\xa1sticas'), (b'PL', b'Planificaci\xc3\xb3n Urbana'), (b'BC', b'Biolog\xc3\xada Celular'), (b'EA', b'Estudios Ambientales'), (b'BO', b'Biolog\xc3\xada de Organismos'), (b'PB', b'Tecnolog\xc3\xada de Procesos Biol\xc3\xb3gicos y Bioqu\xc3\xadmicos')], max_length=6)),
                ('creditos', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)])),
                ('nomAsig', models.CharField(max_length=80)),
                ('progAsig', models.CharField(max_length=20)),
                ('diaHora', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nomAsig',),
            },
        ),
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('nomCoord', models.CharField(choices=[(b'MAT', b'Matem\xc3\xa1ticas'), (b'CB', b'Ciencias Biol\xc3\xb3gicas'), (b'CI', b'Ciencias de la Computaci\xc3\xb3n'), (b'CAN', b'Ciencias de los Alimentos y Nutrici\xc3\xb3n'), (b'FIS', b'F\xc3\xadsica'), (b'QM', b'Qu\xc3\xadmica'), (b'DIC', b'Doctorado Interdisciplinario en Ciencias'), (b'CP', b'Ciencia Pol\xc3\xadtica'), (b'DYA', b'Desarrollo y Ambiente'), (b'EDU', b'Educaci\xc3\xb3n'), (b'EH', b'Estudios Humanos'), (b'FLX', b'Filosof\xc3\xada'), (b'EGE', b'Estudios en Gerencia y Econom\xc3\xada'), (b'LA', b'Ling\xc3\xbc\xc3\xadstica Aplicada'), (b'LIT', b'Literatura'), (b'MUS', b'M\xc3\xbasica'), (b'PSI', b'Psicolog\xc3\xada'), (b'EXT', b'Coordinaci\xc3\xb3n de Comercio Exterior y Licenciatura en Comercio Internacional'), (b'DEI', b'Doctorado en Ingenier\xc3\xada'), (b'ECO', b'Estad\xc3\xadstica Computacional'), (b'IE', b'Ingenier\xc3\xada Electr\xc3\xb3nica'), (b'IT', b'Ingenier\xc3\xada y Tecnolog\xc3\xada El\xc3\xa9ctrica'), (b'GC', b'Ingenier\xc3\xada Geof\xc3\xadsica'), (b'IM', b'Ingenier\xc3\xada Mec\xc3\xa1nica/Civil'), (b'IQ', b'Ingenier\xc3\xada Qu\xc3\xadmica'), (b'MTR', b'Ingenier\xc3\xada de Materiales'), (b'IS', b'Ingenier\xc3\xada de Sistemas'), (b'ITB', b'Ingenier\xc3\xada de Telecomunicaciones/Biom\xc3\xa9dica'), (b'P-CBA', b'Postgrado - Ciencias B\xc3\xa1sicas y Aplicadas'), (b'P-CSH', b'Postgrado - Ciencias Sociales y Humanidades'), (b'P-IT', b'Postgrado - Ingenier\xc3\xada y Tecnolog\xc3\xada')], max_length=15, primary_key=True, serialize=False)),
                ('asignaturas', models.ManyToManyField(blank=True, to='coordinaAsignaturas.Asignatura')),
            ],
            options={
                'verbose_name_plural': 'Coordinaciones',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('carnet', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2050)])),
                ('trimestre', models.CharField(choices=[(b'E-M', b'Enero-Marzo'), (b'A-J', b'Abril-Julio'), (b'S-D', b'Septiembre-Diciembre')], max_length=7)),
                ('asignaturas', models.ManyToManyField(to='coordinaAsignaturas.Asignatura')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[(b'E-M', b'Enero-Marzo'), (b'A-J', b'Abril-Julio'), (b'S-D', b'Septiembre-Diciembre')], max_length=7)),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2050)])),
                ('asignaturas', models.ManyToManyField(to='coordinaAsignaturas.Asignatura')),
                ('coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion')),
            ],
            options={
                'ordering': ('anio',),
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('ciProf', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('nomProf', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coordinaAsignaturas.Usuario')),
                ('coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Coordinacion')),
            ],
            options={
                'verbose_name_plural': 'Coordinadores',
            },
        ),
        migrations.AddField(
            model_name='sesion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='inscripciones',
            field=models.ManyToManyField(to='coordinaAsignaturas.Inscripcion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coordinaAsignaturas.Usuario'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinaAsignaturas.Profesor'),
        ),
    ]
